In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/ai_worker_burnout_attrition_2026.csv")
df.head()

,employee_id,job_role,years_experience,education_level,country,industry,company_size,remote_work_type,team_size,salary_usd_k,...,ai_tools_used_per_day,hours_with_ai_assistance_daily,ai_replaces_my_tasks_pct,ai_adoption_stage,weekly_ai_upskilling_hrs,productivity_score,burnout_score,job_satisfaction_1_5,fear_of_ai_replacement,attrition_risk
0,EMP0001,Data Analyst,7,PhD,India,Healthtech,Large (1000-5000),Fully Remote,8,184,...,1,0.6,37,Experimenting,4.9,59,58,3.0,Low,Medium
1,EMP0002,DevOps Engineer,3,Self-taught,Canada,Fintech,Large (1000-5000),Hybrid,42,51,...,3,0.6,78,Experimenting,6.6,64,47,3.6,Medium,Medium
2,EMP0003,Prompt Engineer,3,PhD,India,Automotive,Startup (<50),Hybrid,37,185,...,4,4.0,23,Optimizing,5.8,50,37,4.6,High,Medium
3,EMP0004,Backend Engineer,18,Master,Germany,Media,Mid (200-1000),Fully Remote,8,131,...,5,4.2,75,Integrating,1.4,77,67,3.0,Low,Medium
4,EMP0005,AI Researcher,5,Bachelor,India,E-commerce,Small (50-200),Fully Remote,21,99,...,7,0.7,61,Experimenting,1.6,58,54,3.6,Medium,Medium

In [2]:
df.shape

(1500, 21)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   employee_id                     1500 non-null   str
 1   job_role                        1500 non-null   str
 2   years_experience                1500 non-null   int64
 3   education_level                 1500 non-null   str
 4   country                         1500 non-null   str
 5   industry                        1500 non-null   str
 6   company_size                    1500 non-null   str
 7   remote_work_type                1500 non-null   str
 8   team_size                       1500 non-null   int64
 9   salary_usd_k                    1500 non-null   int64
 10  primary_ai_tool                 1500 non-null   str
 11  ai_tools_used_per_day           1500 non-null   int64
 12  hours_with_ai_assistance_daily  1500 non-null   float64
 13  ai_replaces_my_tasks_pct        1500 non-null   int64
 14  ai_adoption_stage               1500 non-null   str
 15  weekly_ai_upskilling_hrs        1500 non-null   float64
 16  productivity_score              1500 non-null   int64
 17  burnout_score                   1500 non-null   int64
 18  job_satisfaction_1_5            1500 non-null   float64
 19  fear_of_ai_replacement          1500 non-null   str
 20  attrition_risk                  1500 non-null   str
dtypes: float64(3), int64(7), str(11)
memory usage: 246.2 KB

In [4]:
df.describe()

,years_experience,team_size,salary_usd_k,ai_tools_used_per_day,hours_with_ai_assistance_daily,ai_replaces_my_tasks_pct,weekly_ai_upskilling_hrs,productivity_score,burnout_score,job_satisfaction_1_5
count,1500.000000,1500.000000,1500.000000,1500.00000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,9.947333,24.812667,140.734000,4.05600,4.233733,41.248667,4.985533,57.543333,50.057333,3.334733
std,5.460932,13.682582,59.717429,1.97403,2.148387,21.658214,2.913933,10.726952,11.437771,0.636692
min,1.000000,2.000000,40.000000,1.00000,0.500000,5.000000,0.000000,25.000000,16.000000,1.300000
25%,5.000000,13.000000,91.000000,2.00000,2.400000,22.750000,2.400000,50.000000,42.000000,2.900000
50%,10.000000,25.000000,139.000000,4.00000,4.200000,40.000000,5.000000,57.000000,50.000000,3.300000
75%,15.000000,36.000000,190.000000,6.00000,6.100000,60.000000,7.500000,65.000000,58.000000,3.800000
max,19.000000,49.000000,249.000000,7.00000,8.000000,79.000000,10.000000,95.000000,86.000000,5.000000

In [5]:
df.isna().sum()

employee_id                       0
job_role                          0
years_experience                  0
education_level                   0
country                           0
industry                          0
company_size                      0
remote_work_type                  0
team_size                         0
salary_usd_k                      0
primary_ai_tool                   0
ai_tools_used_per_day             0
hours_with_ai_assistance_daily    0
ai_replaces_my_tasks_pct          0
ai_adoption_stage                 0
weekly_ai_upskilling_hrs          0
productivity_score                0
burnout_score                     0
job_satisfaction_1_5              0
fear_of_ai_replacement            0
attrition_risk                    0
dtype: int64

In [6]:
df.columns

Index(['employee_id', 'job_role', 'years_experience', 'education_level',
       'country', 'industry', 'company_size', 'remote_work_type', 'team_size',
       'salary_usd_k', 'primary_ai_tool', 'ai_tools_used_per_day',
       'hours_with_ai_assistance_daily', 'ai_replaces_my_tasks_pct',
       'ai_adoption_stage', 'weekly_ai_upskilling_hrs', 'productivity_score',
       'burnout_score', 'job_satisfaction_1_5', 'fear_of_ai_replacement',
       'attrition_risk'],
      dtype='str')

In [7]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["burnout_score"].describe()

count    1500.000000
mean       50.057333
std        11.437771
min        16.000000
25%        42.000000
50%        50.000000
75%        58.000000
max        86.000000
Name: burnout_score, dtype: float64

In [10]:
df["attrition_risk"].value_counts()

attrition_risk
Low       724
Medium    691
High       85
Name: count, dtype: int64

In [11]:
numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns

numerical_cols

Index(['years_experience', 'team_size', 'salary_usd_k',
       'ai_tools_used_per_day', 'hours_with_ai_assistance_daily',
       'ai_replaces_my_tasks_pct', 'weekly_ai_upskilling_hrs',
       'productivity_score', 'burnout_score', 'job_satisfaction_1_5'],
      dtype='str')

In [13]:
categorical_cols = df.select_dtypes(include=["str"]).columns

categorical_cols

Index(['employee_id', 'job_role', 'education_level', 'country', 'industry',
       'company_size', 'remote_work_type', 'primary_ai_tool',
       'ai_adoption_stage', 'fear_of_ai_replacement', 'attrition_risk'],
      dtype='str')

In [14]:
for col in categorical_cols:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print("-" * 30)

employee_id
1500
<StringArray>
['EMP0001', 'EMP0002', 'EMP0003', 'EMP0004', 'EMP0005', 'EMP0006', 'EMP0007',
 'EMP0008', 'EMP0009', 'EMP0010',
 ...
 'EMP1491', 'EMP1492', 'EMP1493', 'EMP1494', 'EMP1495', 'EMP1496', 'EMP1497',
 'EMP1498', 'EMP1499', 'EMP1500']
Length: 1500, dtype: str
------------------------------
job_role
12
<StringArray>
[     'Data Analyst',   'DevOps Engineer',   'Prompt Engineer',
  'Backend Engineer',     'AI Researcher', 'AI Ethics Officer',
    'Data Scientist',   'Product Manager',       'ML Engineer',
   'Cloud Architect', 'Software Engineer', 'Frontend Engineer']
Length: 12, dtype: str
------------------------------
education_level
5
<StringArray>
['PhD', 'Self-taught', 'Master', 'Bachelor', 'Bootcamp']
Length: 5, dtype: str
------------------------------
country
10
<StringArray>
[      'India',      'Canada',     'Germany',         'USA',   'Singapore',
 'Netherlands',          'UK',   'Australia',      'Brazil',      'France']
Length: 10, dtype: str
------------------------------
industry
10
<StringArray>
[   'Healthtech',       'Fintech',    'Automotive',         'Media',
    'E-commerce',        'Gaming',    'Consulting', 'Cybersecurity',
        'EdTech',          'SaaS']
Length: 10, dtype: str
------------------------------
company_size
5
<StringArray>
[ 'Large (1000-5000)',      'Startup (<50)',     'Mid (200-1000)',
     'Small (50-200)', 'Enterprise (5000+)']
Length: 5, dtype: str
------------------------------
remote_work_type
3
<StringArray>
['Fully Remote', 'Hybrid', 'On-site']
Length: 3, dtype: str
------------------------------
primary_ai_tool
8
<StringArray>
['GitHub Copilot',        'ChatGPT',     'Midjourney',     'Perplexity',
      'Notion AI',         'Cursor',         'Claude',         'Gemini']
Length: 8, dtype: str
------------------------------
ai_adoption_stage
4
<StringArray>
['Experimenting', 'Optimizing', 'Integrating', 'AI-First']
Length: 4, dtype: str
------------------------------
fear_of_ai_replacement
3
<StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str
------------------------------
attrition_risk
3
<StringArray>
['Medium', 'Low', 'High']
Length: 3, dtype: str
------------------------------